version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
  
  settings:
    errcheck:
      check-type-assertions: false # Disable type assertion checks globally
      check-blank: true
  
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: cmd/
        linters:
          - errcheck
      - path: migrate/
        linters:
          - errcheck
      - path: internal/handler/api_keys\.go
        linters:
          - errcheck
        text: "Error return value is not checked"

formatters:
  enable:
    - goimports
