version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
  
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

formatters:
  enable:
    - goimports

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: cmd/
        linters:
          - errcheck
      - path: migrate/
        linters:
          - errcheck
