import {
  Button, cn, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger,
} from "@idento/ui";
import {
  Barcode, Minus, QrCode, Square, Type, X, type LucideIcon,
} from "lucide-react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import { bindingOptions, displayBinding } from "./bindings";
import type { BadgeElement, BadgeElementType, BadgeTemplateDoc } from "./templateTypes";

export interface ElementsPaneProps {
  doc: BadgeTemplateDoc;
  selectedId: string | null;
  onSelect: (id: string) => void;
  onAdd: (element: BadgeElement) => void;
  onRemove: (id: string) => void;
  // The event's custom field_schema (`event.field_schema ?? []`, same
  // optional-array convention AttendeeFieldsCard.tsx uses) — combined with
  // bindings.ts's STANDARD_BINDINGS via bindingOptions() to tell a
  // recognized binding from an orphaned one (e.g. a custom field renamed
  // or removed from the event after a template bound an element to it).
  fieldSchema: string[];
}

// One entry per BadgeElementType, in "+ Add" menu order (board 4a / task 7
// brief) — doubles as the type-icon lookup and the type-label fallback for
// rows that are neither bound to a source nor (for text) carrying static
// text.
const ELEMENT_TYPES: { type: BadgeElementType; icon: LucideIcon; labelKey: string }[] = [
  { type: "text", icon: Type, labelKey: "badgeAddText" },
  { type: "qrcode", icon: QrCode, labelKey: "badgeAddQrcode" },
  { type: "barcode", icon: Barcode, labelKey: "badgeAddBarcode" },
  { type: "line", icon: Minus, labelKey: "badgeAddLine" },
  { type: "box", icon: Square, labelKey: "badgeAddBox" },
];

const ELEMENT_ICONS = Object.fromEntries(
  ELEMENT_TYPES.map(({ type, icon }) => [type, icon]),
) as Record<BadgeElementType, LucideIcon>;

const ELEMENT_LABEL_KEYS = Object.fromEntries(
  ELEMENT_TYPES.map(({ type, labelKey }) => [type, labelKey]),
) as Record<BadgeElementType, string>;

// New-element defaults per type (task 7 brief, verbatim). `id` is always
// generated by the CALLER via crypto.randomUUID() — same convention
// editorState.ts documents for every other "add" site — so these are
// deliberately `Omit<BadgeElement, "id">`. All x/y/width/height are mm,
// matching BadgeElement throughout templateTypes.ts.
const ELEMENT_DEFAULTS: Record<BadgeElementType, Omit<BadgeElement, "id">> = {
  text: {
    type: "text", x: 5, y: 5, fontSize: 12, fontFamily: "0", text: "", source: "first_name",
  },
  qrcode: {
    type: "qrcode", x: 5, y: 5, width: 15, height: 15, source: "code",
  },
  barcode: {
    type: "barcode", x: 5, y: 5, width: 30, height: 10, source: "code",
  },
  line: {
    type: "line", x: 5, y: 5, width: 30, height: 0.5,
  },
  box: {
    type: "box", x: 5, y: 5, width: 20, height: 10,
  },
};

// Board 4a's Elements pane (P3.1 Task 7): the left column of the badge
// editor's three-pane grid. A flat list of the doc's elements — type icon,
// bound-source chip / static text / type-label fallback, a per-row remove,
// and an "+ Add" menu that creates one of the five element types with its
// exact documented defaults (id from crypto.randomUUID()). Selection is
// fully controlled: `selectedId` comes from the page's reducer state and
// this pane never manages selection locally, so clicking an element on the
// canvas (Task 8) and clicking a row here stay in sync through the same
// single source of truth.
export function ElementsPane({
  doc, selectedId, onSelect, onAdd, onRemove, fieldSchema,
}: ElementsPaneProps) {
  const { t } = useTranslation();

  const knownBindings = React.useMemo(() => new Set(bindingOptions(fieldSchema)), [fieldSchema]);

  function handleAdd(type: BadgeElementType) {
    onAdd({ id: crypto.randomUUID(), ...ELEMENT_DEFAULTS[type] });
  }

  return (
    <div className="flex h-full flex-col gap-3 rounded-lg border border-border p-4" data-testid="badge-pane-elements">
      <div className="flex items-center justify-between gap-2">
        <h3 className="text-body font-medium text-muted-foreground">{t("badgePaneElements")}</h3>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button type="button" variant="outline" size="sm">
              {t("badgeAddMenuLabel")}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {ELEMENT_TYPES.map(({ type, icon: Icon, labelKey }) => (
              <DropdownMenuItem key={type} onSelect={() => handleAdd(type)}>
                <Icon aria-hidden className="size-4" />
                {t(labelKey)}
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      {doc.elements.length === 0 ? (
        <p className="text-caption text-muted-foreground">{t("badgeElementsEmpty")}</p>
      ) : (
        <ul className="flex flex-col gap-1">
          {doc.elements.map((element, index) => {
            const isSelected = element.id === selectedId;
            const Icon = ELEMENT_ICONS[element.type];
            const typeLabel = t(ELEMENT_LABEL_KEYS[element.type]);

            let display: React.ReactNode;
            if (element.source) {
              const known = knownBindings.has(element.source);
              display = (
                <span
                  className="min-w-0 truncate rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-caption text-foreground"
                  title={known ? undefined : t("badgeUnknownBinding", { source: element.source })}
                >
                  {displayBinding(element.source)}
                </span>
              );
            } else if (element.type === "text" && element.text) {
              display = <span className="min-w-0 truncate text-body text-foreground">{element.text}</span>;
            } else {
              display = <span className="min-w-0 truncate text-body text-muted-foreground">{typeLabel}</span>;
            }

            return (
              <li key={element.id} className="flex items-center gap-1">
                <button
                  type="button"
                  aria-current={isSelected ? "true" : undefined}
                  onClick={() => onSelect(element.id)}
                  className={cn(
                    "flex min-w-0 flex-1 items-center gap-2 rounded-md border-l-[3px] px-2 py-1.5 text-left",
                    isSelected
                      ? "border-l-primary bg-primary/5 font-medium"
                      : "border-l-transparent hover:bg-muted",
                  )}
                >
                  <Icon aria-hidden className="size-4 shrink-0 text-muted-foreground" />
                  {display}
                </button>
                <button
                  type="button"
                  aria-label={t("badgeRemoveElementLabel", { index: index + 1, type: typeLabel })}
                  onClick={() => onRemove(element.id)}
                  className="shrink-0 rounded-md p-1.5 text-muted-foreground hover:bg-muted"
                >
                  <X aria-hidden className="size-3.5" />
                </button>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
