name: Feature Request
description: Suggest an idea for Idento
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part would this affect?
      options:
        - Backend (Go API)
        - Web (React Admin)
        - Mobile (Android App)
        - Agent (Printing)
        - Database/Migrations
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: When organizing a conference with 500+ attendees...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought about alternative solutions?
      placeholder: I considered using...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Critical - Blocking current workflow
        - High - Would significantly improve workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: checkboxes
    id: contribute
    attributes:
      label: Willing to Contribute
      description: Would you be willing to work on this feature?
      options:
        - label: Yes, I can submit a PR for this
        - label: Yes, with guidance
        - label: No, just suggesting

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples
