name: Question / Help
description: Ask a question or get help with Idento
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking, please check:
        - [README.md](https://github.com/thevladbog/idento/blob/main/README.md)
        - [DEVELOPMENT.md](https://github.com/thevladbog/idento/blob/main/DEVELOPMENT.md)
        - [Existing issues](https://github.com/thevladbog/idento/issues)

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: Describe your question...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to do? What have you tried so far?
      placeholder: I'm trying to... I've already tried...
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system?
      options:
        - Backend
        - Web
        - Mobile
        - Agent
        - General
        - Setup/Installation
        - Other

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What steps have you already taken?
      placeholder: |
        - Checked README.md
        - Ran `make help`
        - ...

  - type: checkboxes
    id: docs-checked
    attributes:
      label: Documentation Checked
      description: Have you checked the documentation?
      options:
        - label: README.md
        - label: DEVELOPMENT.md
        - label: Project docs/
        - label: Existing issues

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might help us answer your question
